# Generated by Django 5.0 on 2023-12-10 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quienesSomos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='empleado',
            name='nombreRubro',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='fecha de creación'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='image',
            field=models.ImageField(upload_to='empleadosEnQuienesSomos', verbose_name='imagen'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificación'),
        ),
    ]
