# Generated by Django 5.0 on 2023-12-10 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quienesSomos', '0002_alter_empleado_options_empleado_nombrerubro_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='empleado',
            options={},
        ),
    ]
